#!/bin/bash -e
echo PATH=$PATH
export LD_LIBRARY_PATH=$LLVM_HOME/bin-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
cmake -B build -DISPC_PREPARE_PACKAGE=ON -DISPC_INCLUDE_BENCHMARKS=ON -DISPC_CROSS=ON -DGENX_ENABLED=ON -DGENX_DEPS_DIR=$GENX_DEPS
cmake --build build --target package -j4
