name: Tests

on:
  schedule:
    # Run daily - test sse2-avx512 targets @ -O0/-O1/-O2
    - cron:  '0 7 * * *'
  pull_request:
  workflow_dispatch:
    inputs:
      flow_type:
        description: 'Workflow flow type'
        required: true
        default: 'full'
env:
  SDE_TAR_NAME: sde-external-8.59.0-2020-10-05
  LLVM_REPO: https://github.com/ispc/llvm-project
  TARGETS_SMOKE: '["avx2-i32x8"]'
  OPTSETS_SMOKE: "-O2"
  TARGETS_FULL:  '["sse2-i32x4", "sse2-i32x8",
                   "sse4-i8x16", "sse4-i16x8", "sse4-i32x4", "sse4-i32x8",
                   "avx1-i32x4", "avx1-i32x8", "avx1-i32x16", "avx1-i64x4",
                   "avx2-i8x32", "avx2-i16x16", "avx2-i32x4", "avx2-i32x8", "avx2-i32x16", "avx2-i64x4",
                   "avx512knl-i32x16",
                   "avx512skx-i32x8", "avx512skx-i32x16", "avx512skx-i8x64", "avx512skx-i16x32"]'
  OPTSETS_FULL: "-O0 -O1 -O2"

jobs:
  define-flow:
    runs-on: ubuntu-latest
    outputs:
      tests_matrix_targets: ${{ steps.set-flow.outputs.matrix }}
      tests_optsets: ${{ steps.set-flow.outputs.optsets }}
      flow_type: ${{ steps.set-flow.outputs.type }}
    env:
      # for debug purposes
      REF_NAME: ${{ github.ref }}
      EVENT_NAME: ${{ github.event_name }}

      # define rule when to run full flow
      RUN_FULL: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'schedule') ||
                    (github.event_name == 'workflow_dispatch' && github.event.inputs.flow_type == 'full') }}

      # define rule when to run smoke flow
      RUN_SMOKE: ${{ github.event_name == 'pull_request' ||
                    (github.event_name == 'workflow_dispatch' && github.event.inputs.flow_type == 'smoke') }}
    steps:
    - name: Set workflow jobs flow
      id: set-flow
      run: |
        # one and only one var should be set
        [[ $RUN_SMOKE == false && $RUN_FULL == true ]] || [[ $RUN_SMOKE == true && $RUN_FULL == false ]] || ( echo "One and only one env var must be set: RUN_SMOKE or RUN_FULL"; exit 1)
        $RUN_SMOKE && echo "::set-output name=type::smoke" || true
        $RUN_FULL &&  echo "::set-output name=type::full" || true
        # set tests matrix depends on flow
        $RUN_SMOKE && echo "::set-output name=matrix::${TARGETS_SMOKE}" || true
        $RUN_FULL &&  echo "::set-output name=matrix::${TARGETS_FULL}" || true
        # set tests optsets
        $RUN_SMOKE && echo "::set-output name=optsets::${OPTSETS_SMOKE}" || true
        $RUN_FULL &&  echo "::set-output name=optsets::${OPTSETS_FULL}" || true

  linux-build-ispc-llvm11:
    needs: [define-flow]
    runs-on: ubuntu-latest
    container: centos:7
    env:
      LLVM_VERSION: "11.1"
      LLVM_TAR: llvm-11.1.0-centos7-Release-x86.arm.wasm.tar.xz

      L0L_VER: 1.2.3
      VC_INTRINSICS_COMMIT_SHA: "d547de9478277e14896fa6418f6bb07ac07d7a1b"
      SPIRV_TRANSLATOR_COMMIT_SHA: "bea47b3d7528b8be7da88943d884cdb8d045e8a0"
      ISPC_HOME: /usr/local/src/ispc
      LLVM_HOME: /usr/local/src/llvm
      GENX_DEPS: /usr/local/deps

    steps:

    # Centos7 docker image don't have any git
    # which is required do to repo checkout in next step.
    - name: Install git package
      run: |
        # Standard Centos7 packages is git 1.8, GA requires min 2.18.
        yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
        yum install git -y

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        .github/workflows/scripts/install-build-deps.sh

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        cat /proc/cpuinfo

    - name: Build package
      run: |
        .github/workflows/scripts/build-ispc.sh

    - name: Sanity testing (make check-all, make test)
      run: |
        .github/workflows/scripts/check-ispc.sh

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ispc_llvm11_linux
        path: build/ispc-trunk-linux.tar.gz

  linux-test-llvm11:
    needs: [define-flow, linux-build-ispc-llvm11]
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJson(needs.define-flow.outputs.tests_matrix_targets)}}

    steps:
    - uses: actions/checkout@v2
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_llvm11_linux

    - name: Install dependencies and unpack artifacts
      run: |
        .github/workflows/scripts/install-test-deps.sh

    - name: Check environment
      run: |
        cat /proc/cpuinfo

    - name: Running tests
      run: |
        echo PATH=$PATH
        ./alloy.py -r --only="stability current ${{ needs.define-flow.outputs.tests_optsets }}" --only-targets="${{ matrix.target }}" --time --update-errors=FP

    - name: Check
      run: |
        # Print fails to the log.
        git diff --exit-code

    - name: Upload fail_db.txt
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: fail_db.llvm11.${{matrix.target}}.txt
        path: fail_db.txt


